accounts/urls.py
from django.urls import path
from accounts import views


urlpatterns = [
    path("login", views.loginView),
    path("logout", views.logoutView),
    path("signup", views.signupView),
    path("profile", views.profileView),

]

vpn/urls.py
from django.contrib import admin
from django.urls import path, include
from vpnSale import views
from django.conf import settings
from django.conf.urls.static import static
from vpnSale.views import infoV2ray, howToUseV2ray, serverLocationDetails, serverList, serverDetails
from accounts.views import loginView, logoutView, signupView, profileView





urlpatterns = [
    path("", views.index, name="home"),
    path("admin/", admin.site.urls),
    path("vpn/", include("vpnSale.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class profileModel(models.Model):

    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    # Name = models.CharField(max_length = 100)
    # Family = models.CharField(max_length = 100)
    ProfileImage = models.ImageField(upload_to="profileImages/", blank=True, default="static/accounts/images/user-icon2.png")
    Email = models.EmailField()

    Man=1
    Woman=2
    Other=3
    Status_choices = ((Man, "Man"), (Woman, "Woman"), (Other, "Other"))
    Gender = models.IntegerField(choices = Status_choices, null = True)

accounts/forms.py
from django import forms
from accounts.models import profileModel
from django.contrib.auth.models import User




class ProfileRegisterForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class":"form-control",'placeholder':'First name'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class":"form-control",'placeholder':'Last name'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={"class":"form-control",'placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control",'placeholder':'Password'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control",'placeholder':'Email'}))

    class Meta:
        model = profileModel
        fields = ["ProfileImage", "Gender"]

    def clean_username(self):
        username1 = self.cleaned_data['username']
        if User.objects.filter(username = username1).exists():
            raise forms.ValidationError(f"{username1} this username has been taken before")
        return username1

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
import vpnSale.views
import accounts
from django.conf import settings
from django.contrib.auth.decorators import login_required
from accounts.forms import ProfileRegisterForm
from django.contrib.auth.models import User
from accounts.models import profileModel
from .functions import xui_login_func
from vpnSale.models import serverModel


from django.contrib import messages

# Create your views here.


def loginView(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            if request.GET.get("next"):
                return HttpResponseRedirect(request.GET.get("next"))
            else:
                return HttpResponseRedirect(reverse(accounts.views.profileView))
        else:
            context = {
                "username": username,
                "errorMessage": "USERNAME or PASSWORD is wrong!",
            }
            return render(request, "accounts/login.html", context)
    else:
        return render(request, "accounts/login.html", {})


def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse(vpnSale.views.index))


def signupView(request):
    if request.method == "POST":
        profileRegisterForm = ProfileRegisterForm(request.POST, request.FILES)

        if profileRegisterForm.is_valid():
            user = User.objects.create_user(
                username=profileRegisterForm.cleaned_data["username"],
                email=profileRegisterForm.cleaned_data["email"],
                password=profileRegisterForm.cleaned_data["password"],
                first_name=profileRegisterForm.cleaned_data["first_name"],
                last_name=profileRegisterForm.cleaned_data["last_name"],
            )
            user.save()

            profileModel1 = profileModel(
                user=user,
                ProfileImage=profileRegisterForm.cleaned_data["ProfileImage"],
                Gender=profileRegisterForm.cleaned_data["Gender"],
            )

            profileModel1.save()

            return HttpResponseRedirect(reverse(vpnSale.views.index))
        else:
            context = {
                "error_message": profileRegisterForm.errors,
                "formData": profileRegisterForm,
            }

            return render(request, "accounts/signup.html", context)
    else:
        profileRegisterForm = ProfileRegisterForm()

    context = {"formData": profileRegisterForm}

    return render(request, "accounts/signup.html", context)


@login_required
def profileView(request):
    email_request = request.user.email


    client_details_request = xui_login_func.get_clinet_data(email_request).json()
    if client_details_request["success"] == True:
        if client_details_request["obj"] == None:
            client_details = {"status": "No accounts yet"}
            config_gen_result = ""
        else:
            client_details = {"status": "Account is active"}
            inbound_details = xui_login_func.get_inbound_data("1", email_request)
            config_gen_result = xui_login_func.config_gen(
                inbound_details["raw_data"],
                inbound_details["user_id"],
                inbound_details["str_to_json_streamSettings"],
                email_request,
            )
    else:
        client_details = {"status": "Connection refused"}

    profile = request.user.profile

    context = {
        "profile": profile,
        "client_details": client_details,
        "client_config_result": config_gen_result,
    }

    return render(request, "accounts/profile.html", context)

accounts/templates/accounts/login.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Log in
{% endblock %}

{% block titlePage %}

{% endblock %}

{% block bodyblock %}

<div class="col-md-4"></div>
<div class="col-md-4" style="background-color: #b4ca52; border-radius: 20px; margin-bottom: 30px;">
    <form action="" method="post">
        {% csrf_token %}
        {% if messages %}
            {{ messages }}
        {% endif %}
        <img src="../../static/accounts/images/door.jpg" alt="door-logo" style="width: 80px; display: block; margin-left: auto; margin-right: auto; margin-top: 40px;">
        <h1 style="margin: 20px 0; text-align: center;">Log in</h1>
        <h6 style="margin: 20px 0; text-align: center;">Don't have an account?<a href="/accounts/signup" style="text-decoration: none;">Sign up</a></h6>
        <p style="color: red; text-align: center;">{{ username }} : {{ errorMessage }} </p>
        <input type="text" name="username" id="username" placeholder="Username please" value="{{ default_user }}" class="form-control" style="margin-top: 20px; ">
        <input type="password" name="password" id="password" placeholder="Password please" class="form-control" style="margin: 20px 0;">
        <div class="d-grid" style="margin: 30px 0;">
            <input type="submit" value="Continue" class="btn btn-primary">
        </div>

        
    </form>
</div>
<div class="col-md-4"></div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Profile
{% endblock %}


{% block bodyblock %}
<div class="section">
    <div class="container">
        <section>
            <div class="row">
                <div class="col-md-8">
                    <ul class="list-group list-group-flush">
                        {% if profile.user.get_full_name %}
                            <li class="list-group-item"><span style="font-weight: bold;">Name & Family:</span> {{ profile.user.get_full_name }}</li>
                        {% else %}
                            <li class="list-group-item"><span style="font-weight: bold;">Name & Family:</span> Not complated yet</li>
                        {% endif %}
                        <li class="list-group-item"><span style="font-weight: bold;">Username:</span> {{ profile.user.username}}</li>
                        <li class="list-group-item"><span style="font-weight: bold;">Gender:</span> {{ profile.get_Gender_display }}</li>
                        <li class="list-group-item"><span style="font-weight: bold;">Email:</span> {{ profile.user.email}}</li>
                        <!-- <li class="list-group-item"><span style="font-weight: bold;">details:</span> {{ client_details.status }}</li> -->
                        {% if client_details.status == "No accounts yet" %}
                            <li class="list-group-item"><span style="font-weight: bold;">details:</span> <span style="color: red;">{{ client_details.status }}</span></li>
                            <a class="btn btn-primary" href="/vpn/server-list">Go to servers list</a>
                        {% elif client_details.status == "Account is active" %}
                            <li class="list-group-item"><span style="font-weight: bold;">details:</span> <span style="color: green;">{{ client_details.status }}</span></li>
                        {% elif client_details.status == "Connection refused" %}
                            <li class="list-group-item"><span style="font-weight: bold;">details:</span> <span style="color: yellow">{{ client_details.status }}</span></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-md-4">
                    <img class="rounded" src="{{ profile.ProfileImage.url }}" style="width: 200px; " onerror="this.src='../../static/accounts/images/user-icon2.png'; ">
                </div>
            </div>
        </section>
        {% if client_details.status == "Account is active" %}
            <section style="margin-bottom: 40px;">
                <div class="row">
                    <div class="col-md-6">
                        <div class="con-md-3">
                            <label for="config_code1" class="form-label">Your config code:</label>
                            <textarea class="form-control" id="config_code1" rows="4">{{ client_config_result }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-6" style="text-align: center;">
                        <div class="con-md-3">
                            <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data={{ client_config_result }}" class="img-thumbnail" alt="QRcode">
                        </div>
                    </div>
                </div>
            </section>
        {% endif %}
        
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Sign up
{% endblock %}


{% block bodyblock %}

<!-- <div class="col-md-4"></div>
<div class="col-md-4" style="background-color: #b4ca52; border-radius: 20px; margin-bottom: 30px;">
    <form action="" method="post">
        {% csrf_token %}
        <img src="../../static/accounts/images/user-icon.png" alt="door-logo" style="width: 200px; display: block; margin-left: auto; margin-right: auto; margin-top: 40px;">
        <h1 style="margin: 20px 0; text-align: center;">Create an account</h1>
        <h6 style="margin: 20px 0; text-align: center;">Already have an account?<a href="/accounts/login" style="text-decoration: none;">Log in</a></h6>
        <p style="color: red; text-align: center;">{{ username }} : {{ errorMessage }}</p>
        <input type="text" name="username" id="username" placeholder="Username please" class="form-control" style="margin-top: 20px; ">
        <input type="email" name="email" id="email" placeholder="Email please" class="form-control" style="margin-top: 20px; ">
        <input type="password" name="password" id="password" placeholder="Password please" class="form-control" style="margin: 20px 0;">
        <div class="d-grid" style="margin: 30px 0;">
            <input type="submit" value="Sign up" class="btn btn-primary">
        </div>

        
    </form>
</div>
<div class="col-md-4"></div> -->


    <div class="col-md-4"></div>
    <div class="col-md-4" style="background-color: #b4ca52; border-radius: 20px; margin-bottom: 30px;">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <img src="../../static/accounts/images/user-icon.png" alt="door-logo" style="width: 200px; display: block; margin-left: auto; margin-right: auto; margin-top: 40px;">
            <h1 style="margin: 20px 0; text-align: center;">Create an account</h1>
            <h6 style="margin: 20px 0; text-align: center;">Already have an account?<a href="/accounts/login" style="text-decoration: none;">Log in</a></h6>
            <p style="color: red; text-align: center;">{{ error_message }}</p>
            <div class="row">
                <div class="col-md-6">
                    <div class="signup-label">
                        <label for="" class="form-label">Name:</label>
                        {{ formData.first_name }}
                    </div>
                    <div class="signup-label">
                        <label for="" class="form-label">Last name:</label>
                        {{ formData.last_name }}
                    </div>
                    <div class="signup-label">
                        <label for="" class="form-label">Gender: </label>
                        {{ formData.Gender }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="signup-label">
                        <label for="" class="form-label">Email: </label>
                        {{ formData.email }}
                    </div>
                    <div class="signup-label">
                        <label for="" class="form-label">Username: </label>
                        {{ formData.username }}
                    </div>
                    <div class="signup-label">
                        <label for="" class="form-label">Password: </label>
                        {{ formData.password }}
                    </div>
                </div>
                <div class="signup-label">
                <label for="" class="form-label">Profile image:</label>
                {{ formData.ProfileImage }}
                </div>
                <div class="d-grid" style="margin: 30px 0;">
                    <input type="submit" value="Sign up" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-4"></div>

{% endblock %}