vpn/urls.py
from django.contrib import admin
from django.urls import path, include
from vpnSale import views
from django.conf import settings
from django.conf.urls.static import static
from vpnSale.views import infoV2ray, howToUseV2ray, serverLocationDetails, serverList, serverDetails
from accounts.views import loginView, logoutView, signupView, profileView





urlpatterns = [
    path("", views.index, name="home"),
    path("admin/", admin.site.urls),
    path("vpn/", include("vpnSale.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vpnSale/urls.py
from django.urls import path
from vpnSale import views


urlpatterns = [
    path("v2ray-info", views.infoV2ray),
    path("how-to-use-v2ray", views.howToUseV2ray),
    path("server-location-details/<int:location_id>", views.serverLocationDetails),
    path("server-list", views.serverList),
    path("server-details/<int:server_id>", views.serverDetails),
]

vpnSale/models.py
from django.db import models
from accounts.models import profileModel

# Create your models here.

class locationModel(models.Model):
    Name = models.CharField(max_length=100)
    CountryName = models.CharField(max_length=100, null = True)
    CityName = models.CharField(max_length = 100)
    FlagImage = models.ImageField(upload_to="flagImages/")
    MapImage = models.ImageField(upload_to="mapImages/", null=True)
    Description = models.CharField(max_length = 100)

    def __str__(self):
        return "{}-{}".format(self.CountryName, self.CityName)

class serverModel(models.Model):
    locationModel= models.ForeignKey("locationModel", on_delete = models.PROTECT)
    Name = models.CharField(max_length = 100)
    Fixed = 1
    Not_Fixed = 2
    fixed_status = ((Fixed, "Fixed"), (Not_Fixed, "Not Fixed"))
    FixedIpAddress = models.IntegerField(choices=fixed_status, null=True)
    Description = models.CharField(max_length = 100)

    Full = 1
    Ready = 2
    Stoped = 3
    Updating = 4
    Coming_soon = 5
    Status_choices = ((Full, "Full"),(Coming_soon, "Coming soon"), (Ready, "Ready"), (Stoped, "Stoped"), (Updating, "Updating"))
    Status = models.IntegerField(choices=Status_choices, null = True)
    UrlAddress = models.CharField(max_length=100, null = True)


    def __str__(self):
        return "Server {} in {}".format(self.Name, self.locationModel.Name)

class configModel(models.Model):
    serverModel = models.ForeignKey("serverModel", on_delete= models.PROTECT)
    profileModel = models.ForeignKey(profileModel, on_delete= models.PROTECT)
    Name = models.CharField(max_length = 100)
    Type = models.CharField(max_length = 100)
    Time = models.CharField(max_length = 100)
    QRcode = models.ImageField(upload_to="qrcodeImages/")
    ConfigLink = models.CharField(max_length = 300)

    def __str__(self):
        return "config {} on server {} time period {}".format(self.Name, self.serverModel.Name, self.Time)
    

vpnSale/views.py
from django.shortcuts import render
from django.http import HttpResponse
from vpnSale import models
from django.contrib.auth.decorators import login_required
from accounts.models import profileModel
from accounts.functions import xui_login_func
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import accounts

# Create your views here.

def testView(request):
    context = {"1":"aa"}
    return render(request, "vpnSale/firstpage.html", context)

def index(request):

    locations_list = models.locationModel.objects.all()

    my_text = {
        "location_context" : locations_list
    }
    return render(request, "vpnSale/index.html", context = my_text)

def infoV2ray(request):
    my_text = {"text_for_page" : "hello for new world"}
    return render(request, "vpnSale/info-v2ray.html", context=my_text)

def howToUseV2ray(request):
    my_text = {"text_for_page" : "hello for new world"}
    return render(request, "vpnSale/how-to-use.html", context=my_text)

def serverLocationDetails(request, location_id):
    location = models.locationModel.objects.get(pk=location_id)
    context={
        "locationDetails" : location
    }
    return render(request, "vpnSale/server_location_details.html", context)

def serverList(request):
    server = models.serverModel.objects.all()
    context={
        "serverList" : server
    }
    return render(request, "vpnSale/server-list.html", context)

@login_required
def serverDetails(request, server_id):
    
    server_details = models.serverModel.objects.get(pk=server_id)
    context={
        "server__Details" : server_details
    }

    if request.method == "POST" and "get_vpn" in request.POST:
        email_request = request.user.email
        client_add = xui_login_func.add_client(email_request)
        return HttpResponseRedirect(reverse(accounts.views.profileView))
    return render(request, "vpnSale/server_details.html", context)

vpnSale/templates/vpnSale/how-to-use.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    How to use v2ray
{% endblock %}

{% block titlePage %}

{% endblock %}

{% block bodyblock %}

<section class="first_section_howToUse">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
            <div class="top_text_v2ray">
                <h1 id="first_line">How to use v2ray vpn?</h1><br>
                <p class="lead">To use VPN, just copy your config link and add it to the application.</p>
                <p class="lead">If you have never used these softwares and you are not familiar with how to add configuration, watch the following videos to do it easily just with a few steps.</p>
            </div>
        </div>
    </div>
</section>

<section  class="secound_section_howToUse">
    <div class="container">
        <div id="use_videos" class="row">
            <div class="col-md-6">
                <div  class="card" style="width: 98%;">
                    <iframe  src="https://www.youtube.com/embed/wHev33JXyPA?si=q3J4uCMM7ETClj_x" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    <div class="card-body">
                    <h6 class="card-title">On android</h6>
                    <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="width: 98%;">
                    <iframe  src="https://www.youtube.com/embed/wHev33JXyPA?si=q3J4uCMM7ETClj_x" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    <div class="card-body">
                    <h6 class="card-title">On android</h6>
                    <p class="card-text"></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="width: 98%;">
                    <iframe  src="https://www.youtube.com/embed/wHev33JXyPA?si=q3J4uCMM7ETClj_x" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    <div class="card-body">
                    <h6 class="card-title">On android</h6>
                    <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

vpnSale/templates/vpnSale/index.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Main Page
{% endblock %}

{% block titlePage %}
    Welcome to 
{% endblock %}

{% block bodyblock %}
    <!-- <section >
        <div class="container">
            <div class="d-sm-flex align-items-center justify-content-between">
                <div>
                    <h1>0 to 100</h1>
                    <p class="lead"> ljoijo ojo hiosdhf jops josdjf oiphj josi jo sjidoi sdioh soidj oidp</p>
                </div>
                <img class="mainPageImage aligen-item-right" src="../../static/vpnSale/images/6.3.jpg"  alt="">
            </div>
        </div>

    </section> -->

    <section class="first_section">
        <div class="container">
            <div class="d-sm-flex align-items-center justify-content-between">
                <div class="top_text">
                    <h1 id="first_line">The door is closed!</h1>
                    <h1>You are worry about your security!</h1>
                    <h1>You need to change your ip location!</h1>
                    <h1>You need to hide your ip address!</h1>
                    <h1 id="first_line">Just open the door</h1>
                </div>
                <img class="mainPageImage d-none d-sm-block" src="../../static/vpnSale/images/6.3.jpg"  alt="">
            </div>
        </div>
    </section>
    <section id="what-is-vpn" class="text-dark">
        <div class="container">
            <div>
                <div id="what-vpn-text" class="col-md">
                    <h2>What is vpn?</h2>
                    <p class="lead text-dark text-justify">VPN or <span style="font-weight: bold;">“virtual private network.”</span> It’s a service that gives you safe and private access to the internet.</p>
                    <p class="lead">In other words, a VPN connects you to a dedicated server or, more simply, a virtual computer and you connect to the global Internet through that computer.By encrypting your connection, a VPN hides your IP and online activity from spying eyes and keeps your data safe from cybercriminals.</p>
                </div>
            </div>
            <div class="row align-items-center justify-content-between">
                <div id="what-vpn-text" class="col-md">
                    <h2>Why our services?</h2>
                    <div class="reason" id="v2ray-reason">
                        <h5><i class="bi bi-check-circle"></i> Enhanced Privacy</h5>
                        <h5><i class="bi bi-check-circle"></i> Bypassing Censorship</h5>
                        <h5><i class="bi bi-check-circle"></i> Increase Security</h5>
                        <h5><i class="bi bi-check-circle"></i> Geo-Spoofing</h5>
                        <h5><i class="bi bi-check-circle"></i> Customization and Flexibility</h5>
                        <p class="lead">For a long time, we have been working in the field of vpn services in Iran and Russia, especially Iran, which has been under extensive sanctions by various countries for many years, but despite all these problems, our users still have free access to the Internet.</p>
                        <a href="" class="btn btn-primary btn-md mt-3"><i class="bi bi-chevron-right"></i> Read more</a>
                    </div>
                </div>
                <div class="col-md pt-2">
                    <img id="phone-image" class="img-fluid"  src="../../static/vpnSale/images/vpn-on-mobile.jpg" alt="" >
                </div>
            </div>
        </div>
    </section>
    <section id="supported-devices" class="device-section align-items-center justify-content-between">
        <div class="container">
            <h1>Available in all devices</h1>
            <p>Connect with any device and enjoy secure private access to the internet even on public Wi-Fi.</p>
            <div class="app-icons btn btn-outline-secondary">
                <a class="text-light h3" href=""><i class="bi bi-windows"></i></a>
                <br>
                <a class="text-light" href="">Windows</a>
            </div>
            <div class="app-icons btn btn-outline-secondary">
                <a class="text-light h3" href=""><i class="bi bi-apple"></i></a>
                <br>
                <a class="text-light" href="">ios</a>
            </div>
            <div class="app-icons btn btn-outline-secondary">
                <a class="text-light h3" href=""><i class="bi bi-android"></i></a>
                <br>
                <a class="text-light" href="">Android</a>
            </div>
            <div class="app-icons btn btn-outline-secondary">
                <a class="text-light h3" href=""><i class="bi bi-tv"></i></a>
                <br>
                <a class="text-light" href="">AndroidTV</a>
            </div>

        </div>
    </section>
    <section id="our_services" class="services-section align-items-center justify-content-between">
        <div class="container">
            <div class="row">
                <h1 style="padding-bottom: 20px;">Our Services:</h1>
                <h3>VPN with current locations:</h3>
                {% if location_context %}
                    {% for item in location_context %}
                    <div class="col-md-4 col-lg-3">
                        <div class="card" style="width: 98%;">
                            <a href="/vpn/server-location-details/{{ item.id }}"><img src="{{ item.FlagImage.url }}" class="card-img-top" alt=" {{ item }} image"></a>
                            <div class="card-body">
                              <h5 class="card-title">{{ item }} Server</h5>
                              <p class="card-text">With this VPN service, your IP address will be changed to the {{ item }} IP address location.</p>
                              <a href="#" class="btn btn-primary">Get it</a>
                            </div>
                          </div>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
                
            <div class="row">
                <h3>Other services:</h3>
                <div class="col-md-4 col-lg-3">
                    <div class="card" style="width: 98% h; height: 95%;">
                        <img src="../../static/vpnSale/images/global-map.png" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h6 class="card-title">Your own Server with any location</h6>
                          <p class="card-text">You can order any server in any other country you want and we will prepare it for you.</p></p><br><br><br>
                          <a href="#" class="btn btn-primary">Get it</a>
                        </div>
                      </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="card" style="width: 98%; height: 95%;">
                        <img src="../../static/vpnSale/images/windows-server.png" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h6 class="card-title">Setup windows server</h6>
                          <p class="card-text">You can have server with windows server OS to use it as your own computer in other country.</p><br><br><br>
                          <a href="#" class="btn btn-primary">Get it</a>
                        </div>
                      </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="card" style="width: 98%;">
                        <img src="../../static/vpnSale/images/web-browser.png" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h6 class="card-title">Setup web browsing server</h6>
                          <p class="card-text">With this service, you can connect to any requested location and use its browser to trade or do any other work where there is a risk of identifying your IP.</p>
                          <a href="#" class="btn btn-primary">Get it</a>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </section>
    <section id="contactus" class="bg-light">
        <div class="container">
            <h2 class="text-center">
                Contact us
            </h2>
            <div class="row align-items-center justify-content-between">
                <div class="col-md">
                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                      </div>
                      <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Your Message!</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                      </div>
                      <div class="d-grid">
                        <button class="btn btn-primary">Send message</button>
                      </div>
                    </div>
                <div class="col-md">
                    <div class="list-group list-group-flush ">
                        <a href="#" class="list-group-item bg-light">Telegram channel</a>
                        <a href="#" class="list-group-item bg-light">Instagram channel</a>
                        <a href="#" class="list-group-item bg-light">Youtube channel</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    
{% endblock %}

vpnSale/templates/vpnSale/info-v2ray.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    V2ray info
{% endblock %}

{% block titlePage %}

{% endblock %}

{% block bodyblock %}

<section class="first_section_v2ray">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
            <div class="top_text_v2ray">
                <h1 id="first_line">What is a vpn?</h1><br>
                <p class="lead">A VPN, or Virtual Private Network, is a technology that creates a secure and encrypted connection over a less secure network, such as the internet. It allows you to connect to the internet through a server run by a VPN provider, which then encrypts your data and masks your IP address.</p>
                <p>Essentially, a VPN provides privacy and anonymity by creating a private network from a public internet connection. It helps protect your online activities from being monitored, tracked, or intercepted by hackers, your internet service provider (ISP), or any other third parties who might be trying to access or collect your data. VPNs are commonly used for increased security and privacy while browsing the web, accessing sensitive information, or bypassing geographic restrictions on certain websites or content.</p>
            </div>
            <img class="vpn_cloudImage d-none d-sm-block" src="../../static/vpnSale/images/vpn_cloud.jpg"  alt="">
        </div>
    </div>
</section>

<section class="secound_section_v2ray">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
            <img class="v2rayImage d-none d-sm-block" src="../../static/vpnSale/images/V2Ray_logo.png"  alt="">
            <div class="top_text_v2ray">
                <h1 id="first_line">What is v2ray?</h1><br>
                <p class="lead">V2Ray is an open-source network proxy project designed to improve internet privacy, security, and circumvention of censorship. It's a versatile tool known for its flexibility and robustness in handling various networking tasks. Originally developed in Go programming language, V2Ray supports multiple protocols and can work as a proxy server, providing functionalities similar to a VPN.</p>
            </div>
            
        </div>
    </div>
</section>

<section class="third_section_v2ray">
    <div class="container">
        <div class="d-sm-flex align-items-center justify-content-between">
            <div class="top_text_v2ray">
                <h1 id="first_line">Reasons to use v2ray?</h1><br>
                <p class="lead">V2Ray is an open-source network proxy tool designed to improve privacy and security while browsing the internet. There are several reasons why someone might choose to use V2Ray:</p>
                <ol class="v2ray-ol">
                    <li>Enhanced Privacy: V2Ray helps in masking your IP address and encrypting your internet traffic, adding a layer of privacy to your online activities. This can prevent third parties from tracking your online behavior.</li>
                    <br>
                    <li>Bypassing Censorship: In regions where internet access is restricted or certain websites are blocked, V2Ray can help users bypass these restrictions by routing their traffic through servers in other locations where access is not restricted.</li>
                    <br>
                    <li>Increased Security: It provides a secure and encrypted connection, especially when using public Wi-Fi networks, which are vulnerable to hacking and data interception.</li>
                    <br>
                    <li>Geo-Spoofing: V2Ray allows users to appear as if they are accessing the internet from a different location by routing their traffic through servers in other countries. This can help in accessing geo-restricted content or services that are limited to specific regions.</li>
                    <br>
                    <li>Customization and Flexibility: V2Ray offers various configuration options and protocols, allowing users to customize their network settings according to their specific needs.</li>
                </ol>
            </div>
        </div>
    </div>
</section>

{% endblock %}

vpnSale/templates/vpnSale/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block topTitle %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'vpnSale/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vpnSale/css/fontawesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vpnSale/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    


</head>
<body class="d-flex flex-column min-vh-100">
    <!-- <div class="container"> -->
        <div>
          <img class="top_image" src="{% static 'vpnSale/images/4_3.jpg' %}" alt="">
        </div>
        <nav class="navbar navbar-expand-md bg-body-tertiary sticky-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><img class="icon-image" src="../../static/vpnSale/images/5_4.png" alt=""></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#what-is-vpn">What is VPN?</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#supported-devices">Download APPS</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/vpn/server-list">Server list</a>
                  </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                  {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="/accounts/profile">Profile</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" style="color: red;" href="/accounts/logout">Log out</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link" style="color: green;" href="/accounts/login">Log in</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" style="color: blue;" href="/accounts/signup">Sign up</a>
                    </li>
                  {% endif %}

                </ul>
              </div>
            </div>
          </nav>
        <!-- <div class="row-box">
            <h1>{% block titlePage %}{% endblock %}</h1>
            <ul class="btnul">
                <li><a href="$" class="btn btn-success">Main page</a></li>
                <li><a href="vpnSale/list" class="btn btn-success">First page</a></li>
            </ul>
        </div> -->
        <div class="row">
            {% block bodyblock %}{% endblock %}
        </div>
    <!-- </div> -->
    <footer class="main-footer text-center p-2 position-relative mt-auto">
      <p class="lead">Our goal is your freedom</p>
    </footer>
</body>
<script src="{% static 'vpnSale/js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'vpnSale/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'vpnSale/js/fontawesome.js' %}"></script>
<script src="{% static 'vpnSale/js/main.js' %}"></script>
</html>

vpnSale/templates/vpnSale/server-list.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Server List
{% endblock %}

{% block titlePage %}
    
{% endblock %}

{% block bodyblock %}
<section class="first_section">
    <div class="container">
        <div style="padding-bottom: 40px;" class="row">
            <h3 style="padding-bottom: 20px;">Server List:</h3>
            {% if serverList  %}
                {% for item in serverList %}
                    <div class="col-md-3 col-lg-3">
                        <div class="card" style="width: 98%;">
                            <a href="/vpn/server-details/{{ item.id }}"><img src="{{ item.locationModel.FlagImage.url }}" class="card-img-top" alt=" {{ item }} image"></a>
                            <div class="card-body">
                            <h5 class="card-title">Name: {{ item.Name }} </h5>
                            <p class="card-text">This server is located in <span style="color: #587bfd;">{{ item.locationModel }}</span>.</p>
                            <p class="card-text">Server is {{ item.get_Status_display }}.</p>
                            <a href="/vpn/server-details/{{ item.id }}" class="
                            {% if item.Status == item.Full %}
                                btn btn-danger disabled
                            {% elif item.Status == item.Ready %}
                                btn btn-primary
                            {% elif item.Status == item.Stoped %}
                                btn btn-secondary disabled
                            {% elif item.Status == item.Updating %}
                                btn btn-warning disabled
                            {% elif item.Status == item.Coming_soon %}
                                btn btn-success disabled
                            {% endif %}
                            btn btn-primary">Read more ...</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

vpnSale/templates/vpnSale/server_details.html
{% extends "vpnSale/layout.html" %}

{% block topTitle %}
    Server Details
{% endblock %}

{% block titlePage %}
    
{% endblock %}

{% block bodyblock %}
<section class="first_section_server_details">
    <div class="container">
        <div style="padding-bottom: 40px; margin-top: 10px;" class="row">
            <div class="col-md-3">
                <img style="width: 100%;" src="{{ server__Details.locationModel.FlagImage.url }}" class="rounded mx-auto d-block" alt="{{ server__Details.Name }} flag">
                <div class="list-group list-group-flush ">
                    <a href="#" class="list-group-item bg-ligh-item bg-light>t"><h3 style="padding-bottom: 20px;">Server Details:</h3></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">Name: {{ server__Details.Name }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">Country: {{ server__Details.locationModel.CountryName }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">City: {{ server__Details.locationModel.CityName }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">IP Address Type: {{ server__Details.get_FixedIpAddress_display }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">Info: {{ server__Details.Description }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">Info: {{ server__Details.UrlAddress }}</h6></a>
                    <a href="#" class="list-group-item bg-light"><h6 style="padding: 3px;">Status: <span style = "
                    {% if server__Details.Status == server__Details.Full %}
                        color: red ;
                    {% elif server__Details.Status == server__Details.Ready %}
                        color: green ;
                    {% elif server__Details.Status == server__Details.Stoped %}
                        color: gray ;
                    {% elif server__Details.Status == server__Details.Updating %}
                        color: yellow ;
                    {% elif server__Details.Status == server__Details.Coming_soon %}
                        color: blue ;
                    {% endif %}">{{ server__Details.get_Status_display }}</span></h6></a>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="d-grid" style="margin: 10px 0;">
                            <button type="submit" name="get_vpn"  class="btn btn-primary">Get vpn configs</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-9">
                <img style="width: 100%;" src="{{ server__Details.locationModel.MapImage.url }}" class="rounded mx-auto d-block" alt="{{ server__Details.Name }} flag">
            </div>
        </div>
    </div>
</section>
{% endblock %}